@IncludeTypeBackend_HostAddress = https://localhost:7028/api/projectissue

###

GET {{IncludeTypeBackend_HostAddress}}/getissues
Accept: application/json

###

GET {{IncludeTypeBackend_HostAddress}}/gettotalissues
Accept: application/json

###

# @prompt author
GET {{IncludeTypeBackend_HostAddress}}/getissuesbyauthor/{{author}}
Accept: application/json

###

# @prompt username
GET {{IncludeTypeBackend_HostAddress}}/getissuesbyusername/{{username}}
Accept: application/json

###

# @prompt author
POST {{IncludeTypeBackend_HostAddress}}/updateissuesbyauthor/{{author}}
Accept: application/json
Content-Type: application/json

{
    "issues": [
        {
            "projId": "36974559-f8d5-4c07-81db-aff9c56b4fc5",
            "projName": "NewProject",
            "title": "New Issue",
            "date": "May-02-2024",
            "details": "This is a new issue. \uD83D\uDD28",
            "deadline": "May-09-2024",
            "assigned": "SubhamK108",
            "completed": true,
            "priority": "High",
            "author": "SubhamK108"
        }
    ]
}

###

# @prompt username
POST {{IncludeTypeBackend_HostAddress}}/updateissuesbyusername/{{username}}
Accept: application/json
Content-Type: application/json

{
    "issues": [
        {
            "id": "1b3cb41a-c19f-42bf-921b-949a266fb372",
            "projId": "36974559-f8d5-4c07-81db-aff9c56b4fc5",
            "projName": "NewProject",
            "title": "New Issue",
            "date": "May-02-2024",
            "details": "This is a new issue. \uD83D\uDD28",
            "deadline": "May-09-2024",
            "assigned": "SubhamK108",
            "completed": true,
            "priority": "High",
            "author": "SubhamK108"
        },
        {
            "id": "2c1fae23-074a-4868-bb3e-f57a0d199607",
            "projId": "36974559-f8d5-4c07-81db-aff9c56b4fc5",
            "projName": "NewProject",
            "title": "New Issue 2",
            "date": "May-10-2024",
            "details": "This is another new issue.",
            "deadline": "Aug-06-2024",
            "assigned": "SubhamK108",
            "completed": false,
            "priority": "Medium",
            "author": "SubhamK108"
        }
    ]
}

###

# @prompt deadline
GET {{IncludeTypeBackend_HostAddress}}/getissuesforgivendeadline/{{deadline}}
Accept: application/json

###

# @prompt projId Project ID
# @prompt projName Project Name
# @prompt title Issue Title
# @prompt details Issue Details
# @prompt deadline Issue Deadline
# @prompt assigned Issue Assigned To
# @prompt priority Issue Priority
# @prompt author Issue Author
POST {{IncludeTypeBackend_HostAddress}}/addissue
Accept: application/json
Content-Type: application/json

{
    "projId": "{{projId}}",
    "projName": "{{projName}}",
    "title": "{{title}}",
    "details": "{{details}}",
    "deadline": "{{deadline}}",
    "assigned": "{{assigned}}",
    "priority": "{{priority}}",
    "author": "{{author}}"
}

###